// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTzljNchZQZhlw2t_s1hOSQAQU6krCwE',
    appId: '1:790519811057:web:17099212e29a8c8f27d250',
    messagingSenderId: '790519811057',
    projectId: 'funroot-73fd0',
    authDomain: 'funroot-73fd0.firebaseapp.com',
    storageBucket: 'funroot-73fd0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDTzljNchZQZhlw2t_s1hOSQAQU6krCwE',
    appId: '1:790519811057:android:d913ac59778cadc527d250',
    messagingSenderId: '790519811057',
    projectId: 'funroot-73fd0',
    storageBucket: 'funroot-73fd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDTzljNchZQZhlw2t_s1hOSQAQU6krCwE',
    appId: '1:790519811057:ios:d003ad891e57fae127d250',
    messagingSenderId: '790519811057',
    projectId: 'funroot-73fd0',
    storageBucket: 'funroot-73fd0.firebasestorage.app',
    iosBundleId: 'com.example.safedocs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDTzljNchZQZhlw2t_s1hOSQAQU6krCwE',
    appId: '1:790519811057:ios:d003ad891e57fae127d250',
    messagingSenderId: '790519811057',
    projectId: 'funroot-73fd0',
    storageBucket: 'funroot-73fd0.firebasestorage.app',
    iosBundleId: 'com.example.safedocs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDTzljNchZQZhlw2t_s1hOSQAQU6krCwE',
    appId: '1:790519811057:web:47e1f98739a9167027d250',
    messagingSenderId: '790519811057',
    projectId: 'funroot-73fd0',
    authDomain: 'funroot-73fd0.firebaseapp.com',
    storageBucket: 'funroot-73fd0.firebasestorage.app',
  );
}
